// Reciclaí — Catálogo Expandido de Materiais (50+ itens)
// Paleta: Verde Escuro (#1B5E20), Verde Limão (#7CB342), Branco

export type BinColor = 'blue' | 'red' | 'green' | 'yellow' | 'orange' | 'brown' | 'purple' | 'gray';
export type Category = 'plástico' | 'metal' | 'vidro' | 'papel' | 'eletrônico' | 'orgânico' | 'rejeito' | 'especial' | 'medicamento' | 'roupa' | 'construção';
export type ImpactLevel = 'baixo' | 'médio' | 'alto' | 'muito alto';

export interface Material {
  id: string;
  name: string;
  icon: string;
  category: Category;
  recyclable: boolean;
  binColor: BinColor;
  binLabel: string;
  decompositionTime: string;
  impactLevel: ImpactLevel;
  impactScore: number; // 1-5
  steps: string[];
  warnings: string[];
  curiosities: string[];
  specialDisposal?: string;
}

export const materials: Material[] = [
  // PLÁSTICO (10 itens)
  {
    id: 'garrafa-pet',
    name: 'Garrafa PET',
    icon: '🧴',
    category: 'plástico',
    recyclable: true,
    binColor: 'red',
    binLabel: 'Lixeira Vermelha — Plástico',
    decompositionTime: '400 a 500 anos',
    impactLevel: 'muito alto',
    impactScore: 5,
    steps: [
      'Esvazie completamente a garrafa',
      'Enxágue com água para remover resíduos',
      'Retire o rótulo se possível',
      'Amasse a garrafa para ocupar menos espaço',
      'Recoloque a tampa antes de descartar',
    ],
    warnings: [],
    curiosities: [
      'Uma garrafa PET pode ser reciclada em fibras para roupas',
      'O Brasil é o 4º maior produtor de plástico do mundo',
      'Reciclar 1 kg de PET economiza 1,5 kg de petróleo',
    ],
  },
  {
    id: 'sacola-plastica',
    name: 'Sacola Plástica',
    icon: '🛍️',
    category: 'plástico',
    recyclable: true,
    binColor: 'red',
    binLabel: 'Lixeira Vermelha — Plástico',
    decompositionTime: '20 a 30 anos',
    impactLevel: 'muito alto',
    impactScore: 5,
    steps: [
      'Limpe a sacola se necessário',
      'Enrole ou dobre para economizar espaço',
      'Coloque na lixeira vermelha',
      'Sacolas plásticas podem ser reutilizadas',
    ],
    warnings: ['Sacolas plásticas são uma das maiores poluentes dos oceanos'],
    curiosities: [
      'Levam 20 a 30 anos para se decompor',
      'Apenas 1% das sacolas plásticas é reciclado',
      'Um saco plástico é usado em média 12 minutos',
    ],
  },
  {
    id: 'pote-plastico',
    name: 'Pote Plástico',
    icon: '🥣',
    category: 'plástico',
    recyclable: true,
    binColor: 'red',
    binLabel: 'Lixeira Vermelha — Plástico',
    decompositionTime: '100 a 200 anos',
    impactLevel: 'alto',
    impactScore: 4,
    steps: [
      'Enxágue bem o pote',
      'Remova rótulos se possível',
      'Coloque na lixeira vermelha',
      'Potes podem ser reutilizados para armazenamento',
    ],
    warnings: [],
    curiosities: [
      'Potes plásticos são muito versáteis para reutilização',
      'Podem ser transformados em novos potes ou outros plásticos',
      'Reutilizar potes reduz a necessidade de comprar novos',
    ],
  },
  {
    id: 'embalagem-alimento',
    name: 'Embalagem de Alimento',
    icon: '📦',
    category: 'plástico',
    recyclable: true,
    binColor: 'red',
    binLabel: 'Lixeira Vermelha — Plástico',
    decompositionTime: '100 a 150 anos',
    impactLevel: 'alto',
    impactScore: 4,
    steps: [
      'Limpe bem a embalagem',
      'Remova resíduos de alimento',
      'Amasse para economizar espaço',
      'Coloque na lixeira vermelha',
    ],
    warnings: ['Resíduos de alimento podem prejudicar a reciclagem'],
    curiosities: [
      'Embalagens limpas têm maior valor de reciclagem',
      'Podem ser transformadas em novos plásticos',
      'A limpeza é fundamental para qualidade da reciclagem',
    ],
  },
  {
    id: 'canudo-plastico',
    name: 'Canudo Plástico',
    icon: '🥤',
    category: 'plástico',
    recyclable: false,
    binColor: 'gray',
    binLabel: 'Rejeito — Não Reciclável',
    decompositionTime: '200 anos',
    impactLevel: 'muito alto',
    impactScore: 5,
    steps: [
      'Canudos plásticos são muito pequenos para reciclar',
      'Descarte no lixo comum',
      'Prefira canudos reutilizáveis de metal ou bambu',
      'Canudos de papel são uma alternativa melhor',
    ],
    warnings: ['Canudos plásticos prejudicam a vida marinha'],
    curiosities: [
      'Canudos são um dos maiores poluentes dos oceanos',
      'Levam 200 anos para se decompor',
      'Existem alternativas reutilizáveis muito melhores',
    ],
  },
  {
    id: 'filme-plastico',
    name: 'Filme Plástico',
    icon: '📄',
    category: 'plástico',
    recyclable: false,
    binColor: 'gray',
    binLabel: 'Rejeito — Não Reciclável',
    decompositionTime: '100 a 200 anos',
    impactLevel: 'alto',
    impactScore: 4,
    steps: [
      'Filmes plásticos não são recicláveis',
      'Descarte no lixo comum',
      'Tente reutilizar para embrulhar alimentos',
      'Procure alternativas como papel manteiga',
    ],
    warnings: ['Filmes podem prejudicar máquinas de reciclagem'],
    curiosities: [
      'Filmes plásticos entopem máquinas de reciclagem',
      'Podem ser reutilizados para embrulhar alimentos',
      'Papel manteiga é uma alternativa sustentável',
    ],
  },
  {
    id: 'isopor',
    name: 'Isopor',
    icon: '📦',
    category: 'plástico',
    recyclable: false,
    binColor: 'gray',
    binLabel: 'Rejeito — Não Reciclável',
    decompositionTime: 'Mais de 1000 anos',
    impactLevel: 'muito alto',
    impactScore: 5,
    steps: [
      'Isopor é muito difícil de reciclar',
      'Procure pontos especiais de coleta',
      'Descarte no lixo comum se não houver alternativa',
      'Tente reutilizar para proteção de objetos frágeis',
    ],
    warnings: ['Isopor é extremamente prejudicial ao meio ambiente'],
    curiosities: [
      'Isopor leva mais de 1000 anos para se decompor',
      'Ocupa muito espaço em aterros',
      'Poucos lugares conseguem reciclar isopor',
    ],
  },
  {
    id: 'garrafa-agua-plastico',
    name: 'Garrafa de Água Plástica',
    icon: '💧',
    category: 'plástico',
    recyclable: true,
    binColor: 'red',
    binLabel: 'Lixeira Vermelha — Plástico',
    decompositionTime: '400 a 500 anos',
    impactLevel: 'muito alto',
    impactScore: 5,
    steps: [
      'Esvazie completamente a garrafa',
      'Enxágue bem',
      'Amasse para economizar espaço',
      'Coloque na lixeira vermelha',
    ],
    warnings: [],
    curiosities: [
      'Garrafas de água são um dos maiores poluentes',
      'Usar garrafas reutilizáveis economiza dinheiro',
      'Uma garrafa reutilizável substitui 1000 garrafas plásticas',
    ],
  },
  {
    id: 'tupperware',
    name: 'Tupperware',
    icon: '🥡',
    category: 'plástico',
    recyclable: true,
    binColor: 'red',
    binLabel: 'Lixeira Vermelha — Plástico',
    decompositionTime: '100 a 200 anos',
    impactLevel: 'alto',
    impactScore: 3,
    steps: [
      'Limpe bem o tupperware',
      'Remova rótulos',
      'Coloque na lixeira vermelha',
      'Tupperware é muito bom para reutilizar',
    ],
    warnings: [],
    curiosities: [
      'Tupperware é excelente para reutilização',
      'Pode ser usado para armazenar alimentos',
      'Reutilizar reduz a necessidade de novos plásticos',
    ],
  },
  {
    id: 'copo-plastico',
    name: 'Copo Plástico',
    icon: '🥤',
    category: 'plástico',
    recyclable: true,
    binColor: 'red',
    binLabel: 'Lixeira Vermelha — Plástico',
    decompositionTime: '100 a 200 anos',
    impactLevel: 'alto',
    impactScore: 4,
    steps: [
      'Limpe o copo',
      'Remova rótulos se houver',
      'Coloque na lixeira vermelha',
      'Copos reutilizáveis são muito melhores',
    ],
    warnings: [],
    curiosities: [
      'Copos plásticos descartáveis são um grande desperdício',
      'Um copo reutilizável substitui centenas de copos plásticos',
      'Usar copos reutilizáveis economiza dinheiro',
    ],
  },

  // METAL (8 itens)
  {
    id: 'lata-aluminio',
    name: 'Lata de Alumínio',
    icon: '🥫',
    category: 'metal',
    recyclable: true,
    binColor: 'yellow',
    binLabel: 'Lixeira Amarela — Metal',
    decompositionTime: '200 a 500 anos',
    impactLevel: 'alto',
    impactScore: 4,
    steps: [
      'Esvazie completamente a lata',
      'Enxágue com água',
      'Amasse a lata para economizar espaço',
      'Descarte na lixeira amarela',
    ],
    warnings: [],
    curiosities: [
      'O alumínio pode ser reciclado infinitas vezes',
      'Reciclar alumínio economiza 95% de energia',
      'O Brasil é líder em reciclagem de latas',
    ],
  },
  {
    id: 'lata-aco',
    name: 'Lata de Aço',
    icon: '🥫',
    category: 'metal',
    recyclable: true,
    binColor: 'yellow',
    binLabel: 'Lixeira Amarela — Metal',
    decompositionTime: '100 a 200 anos',
    impactLevel: 'alto',
    impactScore: 4,
    steps: [
      'Esvazie a lata',
      'Enxágue bem',
      'Amasse para economizar espaço',
      'Coloque na lixeira amarela',
    ],
    warnings: ['Cuidado com as bordas afiadas'],
    curiosities: [
      'Latas de aço são 100% recicláveis',
      'Podem ser recicladas infinitas vezes',
      'Aço reciclado poupa minério de ferro',
    ],
  },
  {
    id: 'papel-aluminio',
    name: 'Papel Alumínio',
    icon: '📄',
    category: 'metal',
    recyclable: true,
    binColor: 'yellow',
    binLabel: 'Lixeira Amarela — Metal',
    decompositionTime: '200 a 500 anos',
    impactLevel: 'médio',
    impactScore: 3,
    steps: [
      'Limpe bem o papel alumínio',
      'Remova resíduos de alimento',
      'Amasse em uma bolinha',
      'Coloque na lixeira amarela',
    ],
    warnings: ['Papel alumínio sujo pode prejudicar a reciclagem'],
    curiosities: [
      'Papel alumínio é 100% reciclável',
      'Pode ser reutilizado para cozinhar',
      'Alumínio reciclado economiza muita energia',
    ],
  },
  {
    id: 'cobre',
    name: 'Cobre',
    icon: '🔧',
    category: 'metal',
    recyclable: true,
    binColor: 'yellow',
    binLabel: 'Lixeira Amarela — Metal',
    decompositionTime: 'Indeterminado',
    impactLevel: 'médio',
    impactScore: 3,
    steps: [
      'Cobre é muito valioso para reciclar',
      'Procure pontos de coleta de metais',
      'Fios de cobre podem ser levados a sucatarias',
      'Cobre reciclado tem alto valor comercial',
    ],
    warnings: [],
    curiosities: [
      'Cobre é um dos metais mais valiosos para reciclar',
      'Fios de cobre têm alto valor no mercado',
      'Cobre reciclado economiza muita energia',
    ],
  },
  {
    id: 'ferro',
    name: 'Ferro',
    icon: '⚙️',
    category: 'metal',
    recyclable: true,
    binColor: 'yellow',
    binLabel: 'Lixeira Amarela — Metal',
    decompositionTime: 'Indeterminado',
    impactLevel: 'médio',
    impactScore: 3,
    steps: [
      'Ferro é muito bom para reciclar',
      'Procure sucatarias próximas',
      'Ferro tem valor comercial',
      'Ferro reciclado economiza minério',
    ],
    warnings: [],
    curiosities: [
      'Ferro é um dos metais mais reciclados',
      'Sucatarias pagam por ferro',
      'Ferro reciclado economiza muita energia',
    ],
  },
  {
    id: 'latao',
    name: 'Latão',
    icon: '🔔',
    category: 'metal',
    recyclable: true,
    binColor: 'yellow',
    binLabel: 'Lixeira Amarela — Metal',
    decompositionTime: 'Indeterminado',
    impactLevel: 'médio',
    impactScore: 3,
    steps: [
      'Latão é muito valioso',
      'Procure sucatarias',
      'Latão tem alto valor comercial',
      'Pode ser reutilizado para diversos fins',
    ],
    warnings: [],
    curiosities: [
      'Latão é uma liga de cobre e zinco',
      'Tem alto valor no mercado de sucata',
      'Latão reciclado economiza energia',
    ],
  },
  {
    id: 'arame',
    name: 'Arame',
    icon: '🔗',
    category: 'metal',
    recyclable: true,
    binColor: 'yellow',
    binLabel: 'Lixeira Amarela — Metal',
    decompositionTime: 'Indeterminado',
    impactLevel: 'médio',
    impactScore: 2,
    steps: [
      'Arame pode ser reciclado',
      'Procure sucatarias',
      'Arame é vendido por peso',
      'Reutilize para amarrar plantas',
    ],
    warnings: ['Cuidado com as pontas afiadas'],
    curiosities: [
      'Arame é feito de metal reciclável',
      'Pode ser reutilizado de várias formas',
      'Sucatarias pagam por arame',
    ],
  },
  {
    id: 'porca-parafuso',
    name: 'Porca e Parafuso',
    icon: '⚙️',
    category: 'metal',
    recyclable: true,
    binColor: 'yellow',
    binLabel: 'Lixeira Amarela — Metal',
    decompositionTime: 'Indeterminado',
    impactLevel: 'baixo',
    impactScore: 2,
    steps: [
      'Porcas e parafusos são recicláveis',
      'Procure sucatarias',
      'Podem ser reutilizados em projetos',
      'Têm valor comercial',
    ],
    warnings: [],
    curiosities: [
      'Porcas e parafusos podem ser reutilizados',
      'Sucatarias aceitam pequenos metais',
      'Metal reciclado economiza energia',
    ],
  },

  // VIDRO (6 itens)
  {
    id: 'garrafa-vidro',
    name: 'Garrafa de Vidro',
    icon: '🍾',
    category: 'vidro',
    recyclable: true,
    binColor: 'green',
    binLabel: 'Lixeira Verde — Vidro',
    decompositionTime: '1 milhão de anos',
    impactLevel: 'muito alto',
    impactScore: 5,
    steps: [
      'Esvazie a garrafa',
      'Enxágue bem',
      'Remova rótulos se possível',
      'Coloque na lixeira verde',
    ],
    warnings: ['Cuidado com vidro quebrado'],
    curiosities: [
      'Vidro leva 1 milhão de anos para se decompor',
      'Vidro é 100% reciclável',
      'Vidro reciclado economiza energia',
    ],
  },
  {
    id: 'pote-vidro',
    name: 'Pote de Vidro',
    icon: '🥒',
    category: 'vidro',
    recyclable: true,
    binColor: 'green',
    binLabel: 'Lixeira Verde — Vidro',
    decompositionTime: '1 milhão de anos',
    impactLevel: 'alto',
    impactScore: 3,
    steps: [
      'Limpe bem o pote',
      'Remova rótulos',
      'Coloque na lixeira verde',
      'Potes de vidro são ótimos para reutilizar',
    ],
    warnings: [],
    curiosities: [
      'Potes de vidro são excelentes para reutilização',
      'Podem armazenar alimentos indefinidamente',
      'Reutilizar reduz necessidade de novos vidros',
    ],
  },
  {
    id: 'copo-vidro',
    name: 'Copo de Vidro',
    icon: '🥤',
    category: 'vidro',
    recyclable: true,
    binColor: 'green',
    binLabel: 'Lixeira Verde — Vidro',
    decompositionTime: '1 milhão de anos',
    impactLevel: 'médio',
    impactScore: 2,
    steps: [
      'Limpe o copo',
      'Coloque na lixeira verde',
      'Copos de vidro são ótimos para reutilizar',
      'Cuidado com vidro quebrado',
    ],
    warnings: ['Vidro quebrado é perigoso'],
    curiosities: [
      'Copos de vidro duram muito tempo',
      'Podem ser reutilizados indefinidamente',
      'Vidro é 100% reciclável',
    ],
  },
  {
    id: 'frasco-vidro',
    name: 'Frasco de Vidro',
    icon: '🧴',
    category: 'vidro',
    recyclable: true,
    binColor: 'green',
    binLabel: 'Lixeira Verde — Vidro',
    decompositionTime: '1 milhão de anos',
    impactLevel: 'médio',
    impactScore: 2,
    steps: [
      'Limpe bem o frasco',
      'Remova rótulos',
      'Coloque na lixeira verde',
      'Frascos são ótimos para reutilizar',
    ],
    warnings: [],
    curiosities: [
      'Frascos de vidro podem ser reutilizados',
      'Ótimos para armazenar especiarias',
      'Vidro é um material muito durável',
    ],
  },
  {
    id: 'vidro-quebrado',
    name: 'Vidro Quebrado',
    icon: '💔',
    category: 'vidro',
    recyclable: true,
    binColor: 'green',
    binLabel: 'Lixeira Verde — Vidro',
    decompositionTime: '1 milhão de anos',
    impactLevel: 'alto',
    impactScore: 4,
    steps: [
      'Embrulhe bem em jornal',
      'Coloque em uma sacola resistente',
      'Avise o coletor sobre vidro quebrado',
      'Cuidado ao manusear',
    ],
    warnings: ['Vidro quebrado é muito perigoso'],
    curiosities: [
      'Vidro quebrado é reciclável',
      'Deve ser bem embrulhado',
      'Avise coletores sobre vidro quebrado',
    ],
  },
  {
    id: 'espelho',
    name: 'Espelho',
    icon: '🪞',
    category: 'vidro',
    recyclable: false,
    binColor: 'gray',
    binLabel: 'Rejeito — Não Reciclável',
    decompositionTime: '1 milhão de anos',
    impactLevel: 'médio',
    impactScore: 2,
    steps: [
      'Espelhos têm revestimento especial',
      'Não são recicláveis com vidro comum',
      'Descarte no lixo comum',
      'Embrulhe bem para evitar acidentes',
    ],
    warnings: ['Espelhos têm revestimento tóxico'],
    curiosities: [
      'Espelhos têm revestimento de mercúrio',
      'Não podem ser reciclados com vidro',
      'Devem ser descartados com cuidado',
    ],
  },

  // PAPEL (8 itens)
  {
    id: 'caixa-papelao',
    name: 'Caixa de Papelão',
    icon: '📦',
    category: 'papel',
    recyclable: true,
    binColor: 'blue',
    binLabel: 'Lixeira Azul — Papel',
    decompositionTime: '5 anos',
    impactLevel: 'baixo',
    impactScore: 2,
    steps: [
      'Desmonte a caixa',
      'Remova fitas adesivas',
      'Amasse para economizar espaço',
      'Coloque na lixeira azul',
    ],
    warnings: [],
    curiosities: [
      'Papelão é 100% reciclável',
      'Uma árvore produz 8.333 caixas',
      'Papelão reciclado vira novo papelão',
    ],
  },
  {
    id: 'jornal',
    name: 'Jornal',
    icon: '📰',
    category: 'papel',
    recyclable: true,
    binColor: 'blue',
    binLabel: 'Lixeira Azul — Papel',
    decompositionTime: '2 a 6 meses',
    impactLevel: 'baixo',
    impactScore: 1,
    steps: [
      'Separe jornais',
      'Amasse ou dobre',
      'Coloque na lixeira azul',
      'Jornais são muito fáceis de reciclar',
    ],
    warnings: [],
    curiosities: [
      'Jornais são 100% recicláveis',
      'Podem virar novos jornais',
      'Reciclagem de jornal economiza árvores',
    ],
  },
  {
    id: 'revista',
    name: 'Revista',
    icon: '📖',
    category: 'papel',
    recyclable: true,
    binColor: 'blue',
    binLabel: 'Lixeira Azul — Papel',
    decompositionTime: '2 a 6 meses',
    impactLevel: 'baixo',
    impactScore: 1,
    steps: [
      'Separe revistas',
      'Remova capas de plástico se houver',
      'Coloque na lixeira azul',
      'Revistas são muito recicláveis',
    ],
    warnings: [],
    curiosities: [
      'Revistas são 100% recicláveis',
      'Podem virar papel novo',
      'Papel reciclado economiza árvores',
    ],
  },
  {
    id: 'caixa-leite',
    name: 'Caixa de Leite',
    icon: '🥛',
    category: 'papel',
    recyclable: true,
    binColor: 'blue',
    binLabel: 'Lixeira Azul — Papel',
    decompositionTime: '5 anos',
    impactLevel: 'médio',
    impactScore: 2,
    steps: [
      'Enxágue bem a caixa',
      'Amasse para economizar espaço',
      'Coloque na lixeira azul',
      'Caixas recicladas viram papelão',
    ],
    warnings: [],
    curiosities: [
      'Caixas são 75% papel e 25% plástico/alumínio',
      'Caixas recicladas viram papelão',
      'Uma caixa vira 3 caixas novas',
    ],
  },
  {
    id: 'papel-oficio',
    name: 'Papel Ofício',
    icon: '📄',
    category: 'papel',
    recyclable: true,
    binColor: 'blue',
    binLabel: 'Lixeira Azul — Papel',
    decompositionTime: '2 a 6 meses',
    impactLevel: 'baixo',
    impactScore: 1,
    steps: [
      'Separe papéis usados',
      'Amasse ou dobre',
      'Coloque na lixeira azul',
      'Papel é muito fácil de reciclar',
    ],
    warnings: [],
    curiosities: [
      'Papel é 100% reciclável',
      'Pode ser reciclado até 5 vezes',
      'Reciclagem economiza árvores',
    ],
  },
  {
    id: 'caixa-pizza',
    name: 'Caixa de Pizza',
    icon: '🍕',
    category: 'papel',
    recyclable: true,
    binColor: 'blue',
    binLabel: 'Lixeira Azul — Papel',
    decompositionTime: '5 anos',
    impactLevel: 'baixo',
    impactScore: 2,
    steps: [
      'Remova resíduos de alimento',
      'Se muito sujo, descarte no lixo comum',
      'Se limpo, amasse e coloque na lixeira azul',
      'Caixas limpas são recicláveis',
    ],
    warnings: ['Resíduos de alimento prejudicam a reciclagem'],
    curiosities: [
      'Caixas de pizza limpas são recicláveis',
      'Resíduos de gordura prejudicam a reciclagem',
      'Limpeza é fundamental',
    ],
  },
  {
    id: 'embalagem-papel',
    name: 'Embalagem de Papel',
    icon: '📦',
    category: 'papel',
    recyclable: true,
    binColor: 'blue',
    binLabel: 'Lixeira Azul — Papel',
    decompositionTime: '2 a 6 meses',
    impactLevel: 'baixo',
    impactScore: 1,
    steps: [
      'Separe embalagens de papel',
      'Remova plásticos se houver',
      'Amasse para economizar espaço',
      'Coloque na lixeira azul',
    ],
    warnings: [],
    curiosities: [
      'Papel é muito fácil de reciclar',
      'Embalagens de papel são 100% recicláveis',
      'Reciclagem economiza árvores',
    ],
  },
  {
    id: 'papel-aluminio-embalagem',
    name: 'Papel com Alumínio',
    icon: '🍫',
    category: 'papel',
    recyclable: false,
    binColor: 'gray',
    binLabel: 'Rejeito — Não Reciclável',
    decompositionTime: '100 a 200 anos',
    impactLevel: 'médio',
    impactScore: 2,
    steps: [
      'Papel com alumínio não é reciclável',
      'Descarte no lixo comum',
      'Procure alternativas sem alumínio',
      'Reutilize se possível',
    ],
    warnings: [],
    curiosities: [
      'Papel com alumínio é difícil de reciclar',
      'Separa papel de alumínio é complexo',
      'Devem ser descartados juntos',
    ],
  },

  // ELETRÔNICO (8 itens)
  {
    id: 'celular',
    name: 'Celular',
    icon: '📱',
    category: 'eletrônico',
    recyclable: true,
    binColor: 'purple',
    binLabel: 'Descarte Especial — Eletrônicos',
    decompositionTime: 'Indeterminado',
    impactLevel: 'muito alto',
    impactScore: 5,
    steps: [
      'Procure fabricantes com programas de reciclagem',
      'Operadoras de celular geralmente aceitam',
      'Dados devem ser apagados antes',
      'Celulares reciclados recuperam metais preciosos',
    ],
    warnings: ['Celulares contêm baterias tóxicas'],
    curiosities: [
      'Celulares contêm ouro e prata',
      'Baterias de celular são tóxicas',
      'E-waste é o lixo que mais cresce',
    ],
  },
  {
    id: 'computador',
    name: 'Computador',
    icon: '💻',
    category: 'eletrônico',
    recyclable: true,
    binColor: 'purple',
    binLabel: 'Descarte Especial — Eletrônicos',
    decompositionTime: 'Indeterminado',
    impactLevel: 'muito alto',
    impactScore: 5,
    steps: [
      'Procure lojas de informática',
      'Fabricantes têm programas de reciclagem',
      'Dados devem ser apagados antes',
      'Computadores reciclados recuperam metais',
    ],
    warnings: ['Computadores contêm mercúrio e chumbo'],
    curiosities: [
      'Computadores contêm 700 tipos de químicos',
      'Computadores reciclados recuperam ouro',
      'E-waste é o lixo que mais cresce',
    ],
  },
  {
    id: 'notebook',
    name: 'Notebook',
    icon: '💻',
    category: 'eletrônico',
    recyclable: true,
    binColor: 'purple',
    binLabel: 'Descarte Especial — Eletrônicos',
    decompositionTime: 'Indeterminado',
    impactLevel: 'muito alto',
    impactScore: 5,
    steps: [
      'Procure pontos de coleta de eletrônicos',
      'Fabricantes têm programas de reciclagem',
      'Dados devem ser apagados antes',
      'Notebooks reciclados recuperam metais',
    ],
    warnings: ['Notebooks contêm baterias tóxicas'],
    curiosities: [
      'Notebooks contêm materiais valiosos',
      'Baterias são muito tóxicas',
      'Reciclagem recupera metais preciosos',
    ],
  },
  {
    id: 'fone-ouvido',
    name: 'Fone de Ouvido',
    icon: '🎧',
    category: 'eletrônico',
    recyclable: true,
    binColor: 'purple',
    binLabel: 'Descarte Especial — Eletrônicos',
    decompositionTime: 'Indeterminado',
    impactLevel: 'alto',
    impactScore: 4,
    steps: [
      'Procure pontos de coleta de eletrônicos',
      'Lojas de eletrônicos geralmente aceitam',
      'Fones são reciclados em metais e plásticos',
      'Baterias são descartadas com segurança',
    ],
    warnings: [],
    curiosities: [
      'Fones contêm cobre e ouro',
      'Fones reciclados recuperam metais preciosos',
      'Baterias de fones são muito pequenas mas tóxicas',
    ],
  },
  {
    id: 'carregador',
    name: 'Carregador',
    icon: '🔌',
    category: 'eletrônico',
    recyclable: true,
    binColor: 'purple',
    binLabel: 'Descarte Especial — Eletrônicos',
    decompositionTime: 'Indeterminado',
    impactLevel: 'médio',
    impactScore: 3,
    steps: [
      'Procure pontos de coleta de eletrônicos',
      'Lojas de eletrônicos geralmente aceitam',
      'Carregadores são reciclados em metais',
      'Podem ser reutilizados se compatíveis',
    ],
    warnings: [],
    curiosities: [
      'Carregadores contêm cobre e outros metais',
      'Podem ser reutilizados se compatíveis',
      'Reciclagem recupera metais valiosos',
    ],
  },
  {
    id: 'cabo-usb',
    name: 'Cabo USB',
    icon: '🔌',
    category: 'eletrônico',
    recyclable: true,
    binColor: 'purple',
    binLabel: 'Descarte Especial — Eletrônicos',
    decompositionTime: 'Indeterminado',
    impactLevel: 'médio',
    impactScore: 2,
    steps: [
      'Procure pontos de coleta de eletrônicos',
      'Cabos são reciclados em metais',
      'Podem ser reutilizados se compatíveis',
      'Lojas geralmente aceitam cabos',
    ],
    warnings: [],
    curiosities: [
      'Cabos contêm cobre valioso',
      'Podem ser reutilizados',
      'Reciclagem recupera metais',
    ],
  },
  {
    id: 'pilha',
    name: 'Pilha',
    icon: '🔋',
    category: 'eletrônico',
    recyclable: true,
    binColor: 'purple',
    binLabel: 'Descarte Especial — Pilhas',
    decompositionTime: 'Indeterminado',
    impactLevel: 'muito alto',
    impactScore: 5,
    steps: [
      'Procure farmácias ou supermercados',
      'Muitos têm pontos de coleta de pilhas',
      'Pilhas contêm materiais tóxicos',
      'Nunca descarte no lixo comum',
    ],
    warnings: ['Pilhas contêm mercúrio e cádmio muito tóxicos'],
    curiosities: [
      'Uma pilha contamina 600 litros de água',
      'Pilhas contêm mercúrio e cádmio',
      'Nunca devem ir ao lixo comum',
    ],
  },
  {
    id: 'bateria',
    name: 'Bateria',
    icon: '🔋',
    category: 'eletrônico',
    recyclable: true,
    binColor: 'purple',
    binLabel: 'Descarte Especial — Baterias',
    decompositionTime: 'Indeterminado',
    impactLevel: 'muito alto',
    impactScore: 5,
    steps: [
      'Procure pontos de coleta especializados',
      'Fabricantes têm programas de reciclagem',
      'Baterias contêm materiais muito tóxicos',
      'Nunca descarte no lixo comum',
    ],
    warnings: ['Baterias contêm lítio e outros materiais tóxicos'],
    curiosities: [
      'Baterias contêm lítio muito tóxico',
      'Uma bateria contamina muita água',
      'Nunca devem ir ao lixo comum',
    ],
  },

  // ORGÂNICO (4 itens)
  {
    id: 'restos-comida',
    name: 'Restos de Comida',
    icon: '🍎',
    category: 'orgânico',
    recyclable: true,
    binColor: 'brown',
    binLabel: 'Lixo Orgânico',
    decompositionTime: '2 a 6 meses',
    impactLevel: 'baixo',
    impactScore: 1,
    steps: [
      'Separe restos de comida',
      'Procure programas de compostagem',
      'Se não houver, coloque no lixo comum',
      'Restos viram adubo através da compostagem',
    ],
    warnings: [],
    curiosities: [
      'Restos podem virar adubo',
      'Brasil desperdiça 46 milhões de toneladas',
      'Compostagem reduz 30% do lixo doméstico',
    ],
  },
  {
    id: 'folhas-galhos',
    name: 'Folhas e Galhos',
    icon: '🍃',
    category: 'orgânico',
    recyclable: true,
    binColor: 'brown',
    binLabel: 'Lixo Orgânico',
    decompositionTime: '2 a 6 meses',
    impactLevel: 'baixo',
    impactScore: 1,
    steps: [
      'Separe folhas e galhos',
      'Procure programas de compostagem',
      'Folhas podem virar adubo',
      'Galhos podem ser triturados',
    ],
    warnings: [],
    curiosities: [
      'Folhas viram adubo rapidamente',
      'Galhos podem ser triturados',
      'Compostagem é muito benéfica',
    ],
  },
  {
    id: 'casca-fruta',
    name: 'Casca de Fruta',
    icon: '🍌',
    category: 'orgânico',
    recyclable: true,
    binColor: 'brown',
    binLabel: 'Lixo Orgânico',
    decompositionTime: '2 a 6 meses',
    impactLevel: 'baixo',
    impactScore: 1,
    steps: [
      'Separe cascas de frutas',
      'Procure programas de compostagem',
      'Cascas viram adubo muito rapidamente',
      'Ótimas para compostagem',
    ],
    warnings: [],
    curiosities: [
      'Cascas viram adubo em semanas',
      'Muito boas para compostagem',
      'Reduzem lixo doméstico significativamente',
    ],
  },
  {
    id: 'borra-cafe',
    name: 'Borra de Café',
    icon: '☕',
    category: 'orgânico',
    recyclable: true,
    binColor: 'brown',
    binLabel: 'Lixo Orgânico',
    decompositionTime: '2 a 6 meses',
    impactLevel: 'baixo',
    impactScore: 1,
    steps: [
      'Separe borra de café',
      'Procure programas de compostagem',
      'Borra é excelente para adubo',
      'Pode ser usada em plantas',
    ],
    warnings: [],
    curiosities: [
      'Borra de café é excelente adubo',
      'Pode ser usada diretamente em plantas',
      'Muito bom para compostagem',
    ],
  },

  // MEDICAMENTO (3 itens)
  {
    id: 'remedio',
    name: 'Remédio',
    icon: '💊',
    category: 'medicamento',
    recyclable: false,
    binColor: 'purple',
    binLabel: 'Descarte Especial — Medicamentos',
    decompositionTime: 'Indeterminado',
    impactLevel: 'muito alto',
    impactScore: 5,
    steps: [
      'Procure farmácias próximas',
      'Farmácias geralmente têm programas de descarte',
      'Medicamentos nunca devem ir ao lixo comum',
      'Contaminam água e solo',
    ],
    warnings: ['Medicamentos contaminam água e solo'],
    curiosities: [
      'Medicamentos contaminam água',
      'Farmácias têm programas de descarte',
      'Nunca devem ir ao lixo comum',
    ],
  },
  {
    id: 'antibiotico',
    name: 'Antibiótico',
    icon: '💊',
    category: 'medicamento',
    recyclable: false,
    binColor: 'purple',
    binLabel: 'Descarte Especial — Medicamentos',
    decompositionTime: 'Indeterminado',
    impactLevel: 'muito alto',
    impactScore: 5,
    steps: [
      'Procure farmácias',
      'Farmácias têm programas de descarte',
      'Antibióticos nunca devem ir ao lixo',
      'Criam bactérias resistentes na água',
    ],
    warnings: ['Antibióticos criam resistência bacteriana'],
    curiosities: [
      'Antibióticos criam bactérias resistentes',
      'Contaminam água muito facilmente',
      'Farmácias têm programas de descarte',
    ],
  },
  {
    id: 'vitamina',
    name: 'Vitamina',
    icon: '💊',
    category: 'medicamento',
    recyclable: false,
    binColor: 'purple',
    binLabel: 'Descarte Especial — Medicamentos',
    decompositionTime: 'Indeterminado',
    impactLevel: 'médio',
    impactScore: 3,
    steps: [
      'Procure farmácias',
      'Farmácias têm programas de descarte',
      'Vitaminas nunca devem ir ao lixo',
      'Podem contaminar água',
    ],
    warnings: [],
    curiosities: [
      'Vitaminas podem contaminar água',
      'Farmácias têm programas de descarte',
      'Descarte correto é importante',
    ],
  },

  // ROUPA (3 itens)
  {
    id: 'roupa-usada',
    name: 'Roupa Usada',
    icon: '👕',
    category: 'roupa',
    recyclable: true,
    binColor: 'gray',
    binLabel: 'Descarte Especial — Roupas',
    decompositionTime: '5 a 40 anos',
    impactLevel: 'médio',
    impactScore: 3,
    steps: [
      'Separe roupas que não usa mais',
      'Procure programas de doação',
      'Roupas podem ser reutilizadas',
      'Doação é melhor que descartar',
    ],
    warnings: [],
    curiosities: [
      'Roupas podem ser doadas',
      'Reutilização é melhor que reciclagem',
      'Roupas levam 5 a 40 anos para se decompor',
    ],
  },
  {
    id: 'tecido',
    name: 'Tecido',
    icon: '🧵',
    category: 'roupa',
    recyclable: true,
    binColor: 'gray',
    binLabel: 'Descarte Especial — Tecidos',
    decompositionTime: '5 a 40 anos',
    impactLevel: 'médio',
    impactScore: 2,
    steps: [
      'Separe tecidos',
      'Procure programas de reciclagem de tecido',
      'Tecidos podem ser reutilizados',
      'Procure artesãos que usam tecido',
    ],
    warnings: [],
    curiosities: [
      'Tecidos podem ser reutilizados',
      'Artesãos usam tecidos descartados',
      'Reciclagem de tecido economiza água',
    ],
  },
  {
    id: 'sapato',
    name: 'Sapato',
    icon: '👟',
    category: 'roupa',
    recyclable: true,
    binColor: 'gray',
    binLabel: 'Descarte Especial — Sapatos',
    decompositionTime: '40 anos',
    impactLevel: 'médio',
    impactScore: 2,
    steps: [
      'Separe sapatos que não usa mais',
      'Procure programas de doação',
      'Sapatos podem ser doados',
      'Doação é melhor que descartar',
    ],
    warnings: [],
    curiosities: [
      'Sapatos podem ser doados',
      'Levam 40 anos para se decompor',
      'Doação ajuda pessoas necessitadas',
    ],
  },

  // CONSTRUÇÃO (3 itens)
  {
    id: 'tijolos',
    name: 'Tijolos',
    icon: '🧱',
    category: 'construção',
    recyclable: true,
    binColor: 'gray',
    binLabel: 'Descarte Especial — Construção',
    decompositionTime: 'Indeterminado',
    impactLevel: 'médio',
    impactScore: 2,
    steps: [
      'Separe tijolos',
      'Procure pontos de coleta de entulho',
      'Tijolos podem ser reutilizados',
      'Construtoras geralmente aceitam',
    ],
    warnings: [],
    curiosities: [
      'Tijolos podem ser reutilizados',
      'Construtoras aceitam tijolos',
      'Reciclagem de construção economiza recursos',
    ],
  },
  {
    id: 'madeira',
    name: 'Madeira',
    icon: '🪵',
    category: 'construção',
    recyclable: true,
    binColor: 'brown',
    binLabel: 'Orgânico — Madeira',
    decompositionTime: '5 a 10 anos',
    impactLevel: 'baixo',
    impactScore: 2,
    steps: [
      'Separe madeira',
      'Procure programas de reciclagem',
      'Madeira pode ser reutilizada',
      'Carpinteiros geralmente aceitam',
    ],
    warnings: [],
    curiosities: [
      'Madeira pode ser reutilizada',
      'Carpinteiros usam madeira descartada',
      'Reciclagem de madeira economiza árvores',
    ],
  },
  {
    id: 'gesso',
    name: 'Gesso',
    icon: '🧱',
    category: 'construção',
    recyclable: false,
    binColor: 'gray',
    binLabel: 'Rejeito — Não Reciclável',
    decompositionTime: 'Indeterminado',
    impactLevel: 'médio',
    impactScore: 2,
    steps: [
      'Gesso é difícil de reciclar',
      'Procure pontos de coleta de entulho',
      'Descarte em locais apropriados',
      'Nunca descarte em lixo comum',
    ],
    warnings: [],
    curiosities: [
      'Gesso é difícil de reciclar',
      'Pontos de coleta aceitam gesso',
      'Descarte correto é importante',
    ],
  },
];

export const quickBinAnswers: Record<string, { bin: string; color: BinColor; label: string }> = {
  'garrafa pet': { bin: 'Lixeira Vermelha', color: 'red', label: 'Plástico' },
  'plástico': { bin: 'Lixeira Vermelha', color: 'red', label: 'Plástico' },
  'lata': { bin: 'Lixeira Amarela', color: 'yellow', label: 'Metal' },
  'alumínio': { bin: 'Lixeira Amarela', color: 'yellow', label: 'Metal' },
  'papel': { bin: 'Lixeira Azul', color: 'blue', label: 'Papel' },
  'papelão': { bin: 'Lixeira Azul', color: 'blue', label: 'Papel' },
  'jornal': { bin: 'Lixeira Azul', color: 'blue', label: 'Papel' },
  'vidro': { bin: 'Lixeira Verde', color: 'green', label: 'Vidro' },
  'garrafa': { bin: 'Lixeira Verde', color: 'green', label: 'Vidro' },
  'pilha': { bin: 'Descarte Especial', color: 'purple', label: 'Pilhas' },
  'bateria': { bin: 'Descarte Especial', color: 'purple', label: 'Baterias' },
  'celular': { bin: 'Descarte Especial', color: 'purple', label: 'Eletrônicos' },
  'eletrônico': { bin: 'Descarte Especial', color: 'purple', label: 'Eletrônicos' },
  'óleo': { bin: 'Descarte Especial', color: 'orange', label: 'Óleo' },
  'comida': { bin: 'Lixo Orgânico', color: 'brown', label: 'Orgânico' },
  'fruta': { bin: 'Lixo Orgânico', color: 'brown', label: 'Orgânico' },
  'isopor': { bin: 'Lixeira Vermelha', color: 'red', label: 'Plástico' },
  'caixa de leite': { bin: 'Lixeira Azul', color: 'blue', label: 'Papel' },
  'tetra pak': { bin: 'Lixeira Azul', color: 'blue', label: 'Papel' },
  'roupa': { bin: 'Descarte Especial', color: 'gray', label: 'Roupas' },
  'medicamento': { bin: 'Descarte Especial', color: 'purple', label: 'Medicamentos' },
  'remédio': { bin: 'Descarte Especial', color: 'purple', label: 'Medicamentos' },
  'pneu': { bin: 'Descarte Especial', color: 'gray', label: 'Pneus' },
  'lâmpada': { bin: 'Descarte Especial', color: 'purple', label: 'Eletrônicos' },
  'madeira': { bin: 'Orgânico', color: 'brown', label: 'Madeira' },
  'cortiça': { bin: 'Orgânico', color: 'brown', label: 'Cortiça' },
  'acrílico': { bin: 'Lixeira Vermelha', color: 'red', label: 'Plástico' },
  'poliestireno': { bin: 'Lixeira Vermelha', color: 'red', label: 'Plástico' },
  'nylon': { bin: 'Lixeira Vermelha', color: 'red', label: 'Plástico' },
  'borracha': { bin: 'Descarte Especial', color: 'gray', label: 'Borracha' },
  'papel alumínio': { bin: 'Lixeira Amarela', color: 'yellow', label: 'Metal' },
  'cobre': { bin: 'Lixeira Amarela', color: 'yellow', label: 'Metal' },
  'ferro': { bin: 'Lixeira Amarela', color: 'yellow', label: 'Metal' },
  'pizza': { bin: 'Lixeira Azul', color: 'blue', label: 'Papel' },
  'embalagem': { bin: 'Lixeira Vermelha', color: 'red', label: 'Plástico' },
  'sacola': { bin: 'Lixeira Vermelha', color: 'red', label: 'Plástico' },
  'pote': { bin: 'Lixeira Verde', color: 'green', label: 'Vidro' },
  'computador': { bin: 'Descarte Especial', color: 'purple', label: 'Eletrônicos' },
  'fone': { bin: 'Descarte Especial', color: 'purple', label: 'Eletrônicos' },
  'revista': { bin: 'Lixeira Azul', color: 'blue', label: 'Papel' },
};

export const recyclingPoints = [
  {
    id: 1,
    name: 'Ecoponto Centro',
    address: 'Rua das Flores, 123 — Centro',
    distance: '0,3 km',
    hours: 'Seg–Sex: 8h–18h | Sáb: 8h–13h',
    accepts: ['plástico', 'papel', 'vidro', 'metal'],
    lat: -23.5505,
    lng: -46.6333,
  },
  {
    id: 2,
    name: 'Cooperativa Verde Vida',
    address: 'Av. Sustentável, 456 — Jardim',
    distance: '0,8 km',
    hours: 'Seg–Sex: 7h–17h',
    accepts: ['plástico', 'papel', 'metal', 'eletrônico'],
    lat: -23.5525,
    lng: -46.6353,
  },
  {
    id: 3,
    name: 'Farmácia EcoFarma',
    address: 'Rua da Saúde, 789 — Vila Nova',
    distance: '1,2 km',
    hours: 'Todos os dias: 8h–22h',
    accepts: ['pilha', 'bateria', 'remédio'],
    lat: -23.5485,
    lng: -46.6313,
  },
  {
    id: 4,
    name: 'Supermercado BomPreço',
    address: 'Av. Principal, 1000 — Bairro Alto',
    distance: '1,5 km',
    hours: 'Todos os dias: 7h–22h',
    accepts: ['óleo', 'pilha', 'plástico'],
    lat: -23.5545,
    lng: -46.6373,
  },
  {
    id: 5,
    name: 'Ponto de Eletrônicos TechRecicla',
    address: 'Rua da Tecnologia, 321 — Tech Park',
    distance: '2,1 km',
    hours: 'Seg–Sex: 9h–18h',
    accepts: ['eletrônico', 'celular', 'bateria'],
    lat: -23.5465,
    lng: -46.6293,
  },
];

export const educationalContent = [
  {
    id: 'coleta-seletiva',
    title: 'Coleta Seletiva',
    icon: '♻️',
    color: 'eco-green',
    summary: 'Aprenda como funciona a separação de resíduos',
    content: 'A coleta seletiva é a separação dos resíduos sólidos na fonte geradora, de acordo com a sua constituição ou composição. No Brasil, as cores das lixeiras seguem a norma ABNT NBR 10.004.',
  },
  {
    id: 'cores-lixeiras',
    title: 'Cores das Lixeiras',
    icon: '🗑️',
    color: 'eco-blue',
    summary: 'Descubra o que vai em cada lixeira',
    content: 'Azul = Papel, Vermelho = Plástico, Verde = Vidro, Amarelo = Metal, Marrom = Orgânico, Preto = Rejeito, Laranja = Resíduos Perigosos, Roxo = Radioativo.',
  },
  {
    id: 'impacto-ambiental',
    title: 'Impacto Ambiental',
    icon: '🌍',
    color: 'eco-amber',
    summary: 'Entenda como o lixo afeta o planeta',
    content: 'O descarte incorreto de resíduos causa poluição do solo, da água e do ar. Materiais como plástico e vidro levam centenas de anos para se decompor.',
  },
  {
    id: '5rs',
    title: 'Os 5 Rs da Sustentabilidade',
    icon: '🌱',
    color: 'eco-lime',
    summary: 'Recusar, Reduzir, Reutilizar, Reciclar, Recuperar',
    content: 'Os 5 Rs são princípios que guiam um consumo mais consciente e sustentável, priorizando a prevenção da geração de resíduos.',
  },
];

export const quizQuestions = [
  {
    id: 1,
    question: 'Quanto tempo uma garrafa de plástico leva para se decompor?',
    options: [
      { text: '10 anos', correct: false },
      { text: '100 anos', correct: false },
      { text: '400 a 500 anos', correct: true },
      { text: '1000 anos', correct: false },
    ],
    explanation: 'Uma garrafa PET leva entre 400 a 500 anos para se decompor completamente na natureza.',
  },
  {
    id: 2,
    question: 'Qual é a cor da lixeira para metal?',
    options: [
      { text: 'Azul', correct: false },
      { text: 'Amarela', correct: true },
      { text: 'Verde', correct: false },
      { text: 'Vermelha', correct: false },
    ],
    explanation: 'A lixeira amarela é destinada a metais como latas de alumínio e ferro.',
  },
  {
    id: 3,
    question: 'Quantos litros de água 1 litro de óleo contamina?',
    options: [
      { text: '100 litros', correct: false },
      { text: '10 mil litros', correct: false },
      { text: '1 milhão de litros', correct: true },
      { text: '100 mil litros', correct: false },
    ],
    explanation: '1 litro de óleo de cozinha contamina aproximadamente 1 milhão de litros de água.',
  },
  {
    id: 4,
    question: 'Qual é o primeiro R da sustentabilidade?',
    options: [
      { text: 'Reciclar', correct: false },
      { text: 'Reutilizar', correct: false },
      { text: 'Recusar', correct: true },
      { text: 'Recuperar', correct: false },
    ],
    explanation: 'O primeiro R é "Recusar", que significa recusar produtos desnecessários ou prejudiciais ao ambiente.',
  },
  {
    id: 5,
    question: 'Vidro comum é 100% reciclável?',
    options: [
      { text: 'Não, apenas 50%', correct: false },
      { text: 'Sim, 100% reciclável', correct: true },
      { text: 'Não, é muito difícil', correct: false },
      { text: 'Depende da cor', correct: false },
    ],
    explanation: 'Vidro comum é 100% reciclável e pode ser reciclado infinitas vezes sem perder qualidade.',
  },
];
